spring:
  datasource:
    url: &dbURL jdbc:mysql://localhost:3306/kotlin_db?serverTimezone=UTC
    username: &dbUser root
    password: &dbPassword nick4!PR0P
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
